### ISSUE TITLE
This lab is not working

### ISSUE THREAD

**Issue by profbnk** [codefresh-contrib/gitops-certification-examples#220]
error . 

![Screenshot from 2022-10-07 08-54-24](https://user-images.githubusercontent.com/10862078/194461779-ef2ce54e-3819-4115-b9a4-f5743e4276b4.png)

**Comment by profbnk** [comment]
After restart of lab, it's working

**Comment by kostis-codefresh** [comment]
I am glad it worked for you.

Yes sometimes there are some issues with infra of the live labs. Also note that the labs time out (because of resource consumption)

**Comment by profbnk** [comment]
Thank you for your response.

Best regards
Bhagwat Kshirsagar
