### ISSUE TITLE
Bitnami image repo has moved

### ISSUE THREAD

**Issue by cdjg35** [codefresh-contrib/gitops-certification-examples#228]
Bitnami image repo has moved from Quay.io so the sealed secrets exercise doesnt work.

https://github.com/bitnami-labs/sealed-secrets/issues/822#issuecomment-1104116084

**Comment by kostis-codefresh** [comment]
I just tested the lab and it seems to work fine.

This was already fixed https://github.com/codefresh-contrib/gitops-certification-examples/commit/381ec55d6abf26b0935d8e97305a104e51937c6b
