### ISSUE TITLE
Typo in secrets README

### ISSUE THREAD

**Issue by andrewm-aero** [codefresh-contrib/gitops-certification-examples#3]
In https://github.com/codefresh-contrib/gitops-certification-examples/tree/main/secret-app/never-commit-to-git there is what I suspect to be a typo

> Thus you should NEVER commit *encrypted* stuff in git.

Based on my own experience, the name of the directory, plus the text of the course itself, I suspect this is meant to read 

> Thus you should NEVER commit *decrypted* stuff in git.

**Comment by kostis-codefresh** [comment]
Thank you. It was fixed by https://github.com/codefresh-contrib/gitops-certification-examples/pull/7
